feat: Add support for Jython 2.0 and Jython 2.1

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -15,7 +15,7 @@ inputs:
 outputs:
   jython-download-url:
     description: "Random number"
-    value: ${{ steps.jython_installer_url.outputs.download_url }}
+    value: ${{ steps.get_download_url.outputs.download_url }}
 
 runs:
   using: "composite"
@@ -25,43 +25,83 @@ runs:
       with:
         java-version: '8'
         distribution: 'temurin'
+        cache: 'maven'
     
-    - name: Check version
-      shell: bash
-      if: ${{ contains(fromJSON('["2.0", "2.1"]'), inputs.jython-version) }}
-      run: "echo 'Class files not supported' && exit 99"
+    # - name: Check version
+    #   shell: bash
+    #   if: ${{ contains(fromJSON('["2.0", "2.1"]'), inputs.jython-version) }}
+    #   run: | 
+    #     echo 'Class files not supported' && exit 99
 
     - name: Determine Jython installer URL
       shell: bash
-      id: jython_installer_url
+      id: get_download_url
       run: |
-        url_maven="https://repo1.maven.org/maven2/org/python/jython-installer/${{ inputs.jython-version }}/jython-installer-${{ inputs.jython-version }}.jar";
-        url_sourceforge="https://master.dl.sourceforge.net/project/jython/jython/${{ inputs.jython-version }}/jython_installer-${{ inputs.jython-version }}.jar?viasf=1";
-        
-        printf "Testing:\n"
-        printf -- "- Maven      : %s\n" "${url_maven}";
-        printf -- "- SourceForge: %s\n" "${url_sourceforge}";
-        
-        maven_headers="$(curl -sIL "${url_maven}")";
+        _jython_version_no_dot="$(echo "${{ inputs.jython-version }}" | tr -d '.')";
 
-        if echo "${maven_headers}" | grep -qE "HTTP/([0-9.]+) 200 (OK)?"; then
-            download_url="${url_maven}";
+        function test_url () {
+          headers="$(curl -sIL "$1")";
+          echo "${headers}" | grep -qE "HTTP/([0-9.]+) 200 (OK)?";
+        }
+        
+        url_installer_maven="https://repo1.maven.org/maven2/org/python/jython-installer/${{ inputs.jython-version }}/jython-installer-${{ inputs.jython-version }}.jar";
+        url_installer_sourceforge="https://master.dl.sourceforge.net/project/jython/jython/${{ inputs.jython-version }}/jython_installer-${{ inputs.jython-version }}.jar?viasf=1";
+        url_class_sourceforge="https://master.dl.sourceforge.net/project/jython/jython/${{ inputs.jython-version }}/jython-${_jython_version_no_dot}.class?viasf=1";
+        
+        printf "Testing URLs:\n"
+        printf -- "- Maven       (installer): %s\n" "${url_installer_maven}";
+        printf -- "- SourceForge (installer): %s\n" "${url_installer_sourceforge}";
+        printf -- "- SourceForge (class)    : %s\n" "${url_class_sourceforge}";
+        printf "\n";
+
+        if test_url "$url_installer_maven"; then
+            download_url="${url_installer_maven}";
+            installer_type=jar;
+
+        elif test_url "$url_installer_sourceforge"; then
+            download_url="${url_installer_sourceforge}";
+            installer_type=jar;
+
+        elif test_url "$url_class_sourceforge"; then
+            download_url="${url_class_sourceforge}";
+            installer_type=class;
+
         else
-            download_url="${url_sourceforge}";
+            printf "ERROR: Coulnd't find any valid URL!\n" >&2;
+            exit 1;
         fi
 
-        echo "Download URL: ${download_url}"
+        echo "Download URL: ${download_url}";
+
         echo "download_url=${download_url}" >> $GITHUB_OUTPUT
+        echo "installer_type=${installer_type}" >> $GITHUB_OUTPUT
 
 
     - name: Download Jython Installer
+      id: download_installer
       shell: bash
       run: |
-        curl -sL "${{ steps.jython_installer_url.outputs.download_url }}" --output /tmp/jython_installer.jar;
+        case "${{ steps.get_download_url.outputs.installer_type }}" in
+          jar)
+            output_file=/tmp/jython_installer.jar
+          ;;
+          class)
+            output_file=/tmp/jython_installer.class
+          ;;
+          *)
+            printf "ERROR: Unsupported installer type '%s'\n\n" "${{ steps.get_download_url.outputs.installer_type }}";
+            exit 1;
+          ;;
+        esac
+
+        curl -sL "${{ steps.get_download_url.outputs.download_url }}" --output "${output_file}";
+        echo "downloaded_file=${output_file}" >> $GITHUB_OUTPUT
     
     - name: Install Jython
       shell: bash
       run: |
+        case "${{ steps.get_download_url.outputs.installer_type }}" in
+          jar)
             # Installation types:
             # - all       : everything (including src)
             # - standard  : core, mod, demo, doc, ensurepip
@@ -82,29 +122,76 @@ runs:
             #     at org.python.util.install.StandalonePackager.addJarFile(StandalonePackager.java:92)
             #     at org.python.util.install.JarInstaller.inflate(JarInstaller.java:163)
             #     ... 3 more
-
-            # This is why I use the standard installation
-            # java -jar /tmp/jython_installer.jar \
-            #     --silent \
-            #     --directory ${{ inputs.installation-path }} \
-            #     --type standalone;
-
-            java -jar /tmp/jython_installer.jar \
+            #
+            # This is why I use the standard installation...
+            java -jar "${{ steps.download_installer.outputs.downloaded_file }}" \
                 --silent \
                 --directory ${{ inputs.installation-path }} \
                 --type standard;
-                
-            printf "Jython installed in the directory '%s'\n\n" "${{ inputs.installation-path }}"
-            ls -la ${{ inputs.installation-path }}
+          ;;
+          class)
+            # Classic installation does not work:
+            # | Error: A JNI error has occurred, please check your installation and try again
+            # | Exception in thread "main" java.lang.ClassFormatError: Illegal class name "jython-21" in class file jython-21
+            # |       at java.lang.ClassLoader.defineClass1(Native Method)
+            # |       at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
+            # |       at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
+            # |       at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
+            # |       at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
+            # |       at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
+            # |       at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
+            # |       at java.security.AccessController.doPrivileged(Native Method)
+            # |       at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
+            # |       at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
+            # |       at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
+            # |       at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
+            # |       at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:621)
+            # cd /tmp && java -cp ./ jython-21 -o ${{ inputs.installation-path }} demo lib source
             
+            # -------- Manual installation --------
+            # See https://web.archive.org/web/20060702144046/http://www.jython.org/install.html
+            unzip -q "${{ steps.download_installer.outputs.downloaded_file }}" -d ${{ inputs.installation-path }}
+            rm -rf ${{ inputs.installation-path }}/net
+          ;;
+        esac
+
+        printf "Jython installed in the directory '%s'\n\n" ${{ inputs.installation-path }}
+        ls -la ${{ inputs.installation-path }}
+
     - name: Setup Jython alias
       shell: bash
       run: |
-        installation_path="$(sed -r 's/^\s+//; s/\s+$//; s/\/+$//;' <<< "${{ inputs.installation-path }}")"
+        installation_path="$(sed -r 's/^\s+//; s/\s+$//; s/\/+$//;' <<< ${{ inputs.installation-path }})"
 
         mkdir -p ~/.local/bin;
-        printf 'java -jar %s/jython.jar "$@"\n' "${installation_path}" >> ~/.local/bin/jython;
-        chmod +x ~/.local/bin/jython;
-        echo ~/.local/bin >> $GITHUB_PATH
 
-        cat ~/.local/bin/jython
+        # ------------------ Create 'jython' script ------------------
+        if [[ -d "${installation_path}/org" ]]; then
+        cat - <<EOF | sed -r 's/^\s*//' >> ~/.local/bin/jython && chmod +x ~/.local/bin/jython
+          #!/bin/bash
+          java -classpath ${installation_path}/jython.jar org.python.util.jython -Dpython.home="${installation_path}" "\$@";
+        EOF
+        elif [[ -f ${installation_path}/jython.jar ]];
+        cat - <<EOF | sed -r 's/^\s*//' >> ~/.local/bin/jython && chmod +x ~/.local/bin/jython
+          #!/bin/bash
+          java -jar ${installation_path}/jython.jar -Dpython.home="${installation_path}" "\$@";
+        EOF
+        else
+          printf "ERROR: Cannot create 'jython' script.\n\n";
+          exit 1
+        fi
+
+        # ------------------ Create 'jythonc' script ------------------
+        # (https://www.jython.org/jython-old-sites/archive/22/jythonc.html)
+        if [[ -f ${installation_path}/jythonc ]]; then
+          ln -snf ${installation_path}/jythonc ~/.local/bin/jythonc;
+        elif [[ -f ${installation_path}/Tools/jythonc/jythonc.py ]]; then
+        cat - <<EOF | sed -r 's/^\s*//' >> ~/.local/bin/jythonc && chmod +x ~/.local/bin/jythonc
+          #!/bin/bash
+          ~/.local/bin/jython "${installation_path}/Tools/jythonc/jythonc.py" "\$@";
+        EOF
+        else 
+          printf "WARNING: Cannot create 'jythonc' script (did not find 'jythonc' or 'jythonc.py').\n\n";
+        fi
+
+        echo ~/.local/bin >> $GITHUB_PATH
